### ISSUE TITLE
Shows multiple identical answers

### ISSUE THREAD

**Issue by lgommans** [alexgreene/WikiQuiz#5]
Any article I try gives duplicate answers, sometimes three and usually two.

![](https://snag.gy/JsNTAt.jpg)

![](https://snag.gy/zbU9hf.jpg)

Even the demo article that you show in the readme, motorcycles, doesn't work at all. It asks obvious questions or proposes duplicate answers. At least all duplicates are counted as correct.

**Comment by alexgreene** [comment]
This is a known issue and it has to do with the simplicity of the grammar for finding sentences in the article that would make good questions. Because the wrong answers are selected at random from the total pool of answers, it is possible to see duplicates if the script does not have a large enough pool to choose from. Thanks for pointing this out- this would certainly be addressed in a further update.
